# Generated by Django 5.1.4 on 2024-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('full_content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
